<a href="https://colab.research.google.com/github/MuhammadHammad02/Python/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a


array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[1])

[4 5 6]


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
a



array([0., 0.])

In [ ]:
a2=np.zeros(2)
a2

array([0., 0.])

In [ ]:
a = np.ones(2)
a

array([1., 1.])

In [ ]:
b=np.empty(2)
b

array([1., 1.])

In [ ]:
c= np.arange(5)
c

array([0, 1, 2, 3, 4])

In [ ]:
d= np.arange(2,9,2)
d


array([2, 4, 6, 8])

In [ ]:
e=np.arange(3,16,2)
e


array([ 3,  5,  7,  9, 11, 13, 15])

In [ ]:
e= np.arange(3,16,3)
e

array([ 3,  6,  9, 12, 15])

In [ ]:
f= np.linspace(0, 10, num=5)
f

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])